### ISSUE TITLE
Error loading script server.lua

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_robbery#1]
Hi Sighmir,

Just to report an issue  ..

Error loading script server.lua in resource vrp_robbery: [string "..."]:126: attempt to concatenate a nil value (local 'identifier')
stack traceback:
        [string "..."]:126: in field 'getInterface'
        server.lua:6: in main chunk

**Comment by Sighmir** [comment]
If this line is presenting issue related to the second argument which would be the "identifier" then it means part of your vRPex is still the old vRP... almost all of the vRPex scripts have that same function.
vRPclient = Tunnel.getInterface("vRP")

**Comment by zalijr** [comment]
Same : 
Error loading script server.lua in resource vrp_robbery: [string "..."]:126: attempt to concatenate a nil value (local 'identifier')
stack traceback:
[string "..."]:126: in field 'getInterface'
server.lua:6: in main chunk

**Comment by Sighmir** [comment]
This issue is already answered, you are using vRP instead of vRPex.
